baseURL = 'https://TonyAshworth.github.io/emily-cookbook-hugo/'
languageCode = 'en-us'
title = "Emily's Cookbook"

# Custom Emily theme with portrait recipe cards and working search
theme = "emily"

# Enable emoji support
enableEmoji = true

# Pagination
[pagination]
  pagerSize = 12

[params]
  # Site info
  description = "A collection of delicious gluten-free recipes tested and perfected in our home kitchen."
  author = "Emily Ashworth"
  
  # Homepage intro 
  introTitle = "Welcome to Emily's Cookbook 🍴"
  introDescription = "A collection of over 100 delicious gluten-free recipes tested and perfected in our home kitchen. From comfort food classics to international flavors, find your next favorite dish here!"
  
  # Main sections for the homepage cards
  mainSections = ["recipes"]
  
  # Custom copyright
  copyright = "Copyright © 2025 - Emily Ashworth · All rights reserved"

# Navigation menu
[menu]
  [[menu.main]]
    name = "All Recipes"
    url = "/recipes/"
    weight = 10
  [[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 20
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 30

# Output directory (GitHub Actions will use this)
# publishDir = "public" # This is the default, so we don't need to specify it

# Enable taxonomies for recipe categorization
[taxonomies]
  tag = "tags"

# Required outputs for search functionality
[outputs]
  home = ["HTML", "RSS", "JSON"]

# Build settings for search
[build]
  writeStats = true

# Markup settings
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    style = "github"
