baseURL = 'https://TonyAshworth.github.io/emily-cookbook-hugo/'
languageCode = 'en-us'
title = "Emily's Cookbook"

# Required for PaperMod theme
theme = "PaperMod"

# Pagination
[pagination]
  pagerSize = 10

# Enable emoji support
enableEmoji = true

[params]
  # Site info
  description = "A collection of delicious gluten-free recipes tested and perfected in our home kitchen."
  author = "Emily Ashworth"
  
  # Theme settings
  defaultTheme = "auto" # auto, light, dark
  disableThemeToggle = false
  
  # Home page mode - use home-info mode
  mode = "home-info"
  
  # Home page settings  
  [params.homeInfoParams]
    Title = "Welcome to Emily's Cookbook 🍴"
    Content = "A collection of over 100 delicious gluten-free recipes tested and perfected in our home kitchen. From comfort food classics to international flavors, find your next favorite dish here!"
  
  # Features
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowWordCount = true
  ShowToc = true
  TocOpen = false
  ShowRssButtonInSectionTermList = true
  
  # SEO
  [params.fuseOpts]
    isCaseSensitive = false
    shouldSort = true
    location = 0
    distance = 1000
    threshold = 0.4
    minMatchCharLength = 0
    keys = [ "title", "permalink", "summary", "content" ]
    
  # Social icons
  [[params.socialIcons]]
  name = "github"
  url = "https://github.com/TonyAshworth/emily-cookbook-hugo"
  
  [[params.socialIcons]]
  name = "rss"
  url = "/index.xml"
  
[menu]
  [[menu.main]]
    name = "All Recipes"
    url = "/recipes/"
    weight = 10
  [[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 20
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 30

# Output directory (GitHub Actions will use this)
# publishDir = "public" # This is the default, so we don't need to specify it

# Enable taxonomies for recipe categorization
[taxonomies]
  tag = "tags"
  category = "categories"

# Markup settings
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
